name: Deploy docker

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@5.10.0
        with:
          images: prr133f/avito

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}

      - name: Generate artifacts
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/prr133f/avito
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
    
